### ISSUE TITLE
Update jline to version 3.X

### ISSUE THREAD

**Issue by martin-v** [retest/recheck.cli#113]
Update jline to version 3 regarding 
https://github.com/remkop/picocli/blob/master/picocli-shell-jline3/README.md

**Comment by beatngu13** [comment]
JLine code hasn't been merged so far, so the update should be part of #93. I already mentioned it here: https://github.com/retest/recheck.cli/pull/93/files#r308622069

**Comment by martin-v** [comment]
The current version is working and we want to make the 1.3.0 release soon. That's why I separated the update from the PR. If this is the only thing missing in #93 please approve.

**Comment by beatngu13** [comment]
I have removed JLine in https://github.com/retest/recheck.cli/pull/120/commits/7e959996f18f9caf46f3c45c4273c9375368738f. From the commit message:

>Hard to test with System Rules, not well-documented, and we only need to read a single line.

Therefore, I close this issue.
