### ISSUE TITLE
Recheck logo doesn't work on Windows 

### ISSUE THREAD

**Issue by ivonx** [retest/recheck.cli#84]
![recheckVersion](https://user-images.githubusercontent.com/27949268/59425975-4e245600-8dd7-11e9-85c0-c00f46a91c58.PNG)

Question marks appear instead of hooks on Windows

**Comment by Creepow** [comment]
Changed the logo to display #'s when on windows (work around).

**Comment by beatngu13** [comment]
Let's close this, workaround is sufficient IMO. 👍
